### ISSUE TITLE
1.21.11 villagers won't get work

### ISSUE THREAD

**Issue by amin0eternity** [frikinjay/morevillagers#35]
i installed the mod and was about to use the mod in my hardcore world but as many time as i tried it they didn't get the work, and was just running around, then i made a new creative world to test and none of workstations was working, none of villagers was getting a job

**Comment by frikinjay** [comment]
Fixed in 1.25.12.3

**Comment by Lykeios1221** [comment]
I still faced the same issue with 1.25.13.3

Neoforge: 21.11 30-beta
Villaga API: 1.26.0.1
Minecraft version: 1.21.11

**Comment by frikinjay** [comment]
1.25.13.3 of morevillagers does not exist, update to 1.25.12.4 and VillagerAPI 1.26.01.1

**Comment by Lykeios1221** [comment]
> 1.25.13.3 of morevillagers does not exist, update to 1.25.12.4 and VillagerAPI 1.26.01.1

Sry typo, I was using 1.25.12.3, because 1.25.12.4 not yet available for version 1.21.11

Edited:
I managed to get it work after manually download the resource from GitHub and add into the villagepack, not sure whether it is the default behaviour
